# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [3]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [5]:
### [your code here]
print(np.__version__)


2.2.5


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [26]:
### [your code here]
import numpy as np
a=np.random.randint(0, 9, size=(2,3,5))
type(a)




numpy.ndarray


### 4. Print a.


In [52]:
### [your code here]
print(a)



[[[7 4 6 2 5]
  [7 2 6 7 1]
  [6 2 5 5 1]]

 [[5 7 1 1 6]
  [5 7 8 1 7]
  [0 2 7 3 6]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [31]:
### [your code here]
b=np.ones((5,2,3))


### 6. Print b.


In [36]:
### [your code here]
print(b)
print(type(b))

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
<class 'numpy.ndarray'>



### 7. Do a and b have the same size? How do you prove that in Python code?


In [48]:
#Yes they have the same size
size_of_a=a.size
size_of_b=b.size
print(f"Since of a = " , size_of_a)
print(f"Since of b = ", size_of_b)
print(f"Hence they are the same")

Since of a =  30
Since of b =  30
Hence they are the same


In [49]:
### [your code here]

a=np.random.randint(0, 9, size=(2,3,5))
b=np.ones((5,2,3))
size_of_a = a.size
size_of_b=b.size
print(f'Since of a is ' , size_a)
print(f'Since of a is ' , size_of_b)
print (f"size comparision between a and b is =", {size_a==size_of_b})


Since of a is  30
Since of a is  30
size comparision between a and b is = {True}



### 8. Are you able to add a and b? Why or why not?


In [54]:
### We are not about to add a and b together directly because they do not have the same diemensions 2x3x5 3 vs 2x3x5
### [your code here]
import numpy as np ### I know i dont have to reimport , i do this to get used to the syntax
first_array = a
second_array = b
addition_fo_array = first_array + second_array
print(addition_fo_array)




ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [11]:
### [your code here]
import numpy as np
a=np.random.randint(0, 9, size=(2,3,5))
b=np.ones((5,2,3))
c=np.reshape(b , (2, 3, 5))

print(c)



[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [12]:
### [your code here]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [29]:
### [your code here]




### 12. Multiply a and c. Assign the result to e.


In [30]:
### [your code here]




### 13. Does e equal to a? Why or why not?


In [31]:
### [your code here]





### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [32]:
### [your code here]




### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [33]:
### [your code here]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [34]:
### [your code here]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [35]:
### [your code here]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]